### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [Foundation-Devices/tor#23]
https://github.com/Foundation-Devices/tor/blob/main/LICENSE

**Comment by sethforprivacy** [comment]
Hey @SamsungGalaxyPlayer, we're on it! Will be licensing as GPLv3.

**Comment by icota** [comment]
Licences are in https://github.com/Foundation-Devices/tor/tree/main/LICENSES

`cargokit` is MIT and everything else GPLv3 or later.
