### ISSUE TITLE
Build failed on the windows

### ISSUE THREAD

**Issue by H3mnz** [Foundation-Devices/tor#29]
When I try to run on the windows, these errors happen.

  SEVERE: error[E0433]: failed to resolve: could not find `Resource` in `rlimit`
  SEVERE: error[E0425]: cannot find function `getrlimit` in crate `rlimit`

Exception: Build process failed.

**Comment by icota** [comment]
Thank you for reporting @H3mnz. Seems to be happening because some of our utility functions (to increase the number of open files) are not available on Windows. 

Since this is not strictly necessary on desktop platforms I'll see if it's possible to omit this functionality.

**Comment by icota** [comment]
I don't actually have a Windows machine to test this. @H3mnz can you please try using the branch from https://github.com/Foundation-Devices/tor/pull/30?
